### ISSUE TITLE
How to build and run this?

### ISSUE THREAD

**Issue by vanfanel** [jhhoward/Faux86#1]
Hi there, jjhoward

Is faux86 already build-able and runable on the Pi? What kind of 86 machine does it implement? I see no docs and I am very curious...

Thanks!

**Comment by jhhoward** [comment]
If you just want to run but don't want to go through the process of compiling, have a look at the releases page.
https://github.com/jhhoward/Faux86/releases

Otherwise you can build from source. You will need to install the circle library for building for the Pi:
https://github.com/rsta2/circle

Be sure to follow the instructions for building circle carefully, you will also need to compile the extra modules in circle's addon directory.

Once you have done this, you might need to edit Faux86's Makefile to ensure that CIRCLEHOME is pointing to the circle library's source directory. From there you should be able to just run make to build a kernel.img. You will need to add this plus the Raspberry Pi bootcode.bin and start.elf to the Pi's SD card. You will also need to copy the binaries in the Faux86 data folder.

**Comment by vanfanel** [comment]
@jhhoward Sorry! I had not seen your answer! Thanks a lot for the detailed answer, even if it's late :+1: 

Are you still developing Faux86? Is it supposed to work on a Pi4?

**Comment by jhhoward** [comment]
I can't say for sure about a Pi 4 version as I don't have one to test on, but it should be possible to build a Pi 4 compatible version with the latest version of the Circle library. 

I'm not actively working on it right now as I don't really have the time to but will probably come back to it again when I have more time :)

**Comment by vanfanel** [comment]
@jhhoward Thanks! A Pi4 build would be very interesting, because of the recently announced Pi 400 computer, just imagine a PC running there baremetal...
